export interface DemoStatusHistory {
  status: string;
  changedAt: string;
  changedBy?: string;
  note?: string;
}

export interface DemoReport {
  id: string;
  title: string;
  description: string;
  category: string;
  severity: string;
  status: string;
  priorityScore: number;
  aiConfidence?: number;
  aiSummary?: string;
  latitude: number;
  longitude: number;
  address: string;
  imageUrl: string;
  submittedBy: {
    id: string;
    name: string;
    username: string;
    avatarUrl: string;
  };
  upvotes: number;
  hasUserUpvoted: boolean;
  verifications: number;
  comments: number;
  assignedTo?: {
    type: "department" | "worker";
    name: string;
    workerId?: string;
  };
  captureMethod: "CAMERA" | "UPLOAD";
  capturedAt?: string;
  createdAt: string;
  updatedAt: string;
  resolvedAt?: string;
  statusHistory: DemoStatusHistory[];
}

export const demoReports: DemoReport[] = [
  {
    id: "rpt_001",
    title: "Large pothole on Gandhiji Road near bus stand",
    description: "Deep pothole approximately 2 feet wide, causing vehicles to swerve dangerously. Multiple two-wheelers have already fallen here this week.",
    category: "POTHOLE",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    priorityScore: 94,
    aiConfidence: 0.97,
    aiSummary: "Large, deep pothole in high-traffic urban corridor. Immediate risk to two-wheeler riders. Priority intervention required.",
    latitude: 10.7870,
    longitude: 79.1378,
    address: "Gandhiji Road, near Thanjavur Central Bus Stand, Thanjavur - 613001",
    imageUrl: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=800",
    submittedBy: { id: "user_demo_citizen_001", name: "Arjun Mehta", username: "arjun_m", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=arjun" },
    upvotes: 47,
    hasUserUpvoted: false,
    verifications: 18,
    comments: 6,
    assignedTo: { type: "department", name: "Roads & Infrastructure" },
    captureMethod: "CAMERA",
    capturedAt: "2026-06-23T08:14:00Z",
    createdAt: "2026-06-23T08:17:00Z",
    updatedAt: "2026-06-24T10:00:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-23T08:17:00Z", note: "Report submitted" },
      { status: "IN_PROGRESS", changedAt: "2026-06-24T09:00:00Z", changedBy: "Priya Subramaniam", note: "Assigned to Roads & Infrastructure dept. Crew scheduled." },
    ],
  },
  {
    id: "rpt_002",
    title: "Illegal garbage dumping near Sivaganga Park",
    description: "A large mound of construction debris and household waste has been dumped illegally beside the park entrance. Stench is unbearable and blocking pedestrian access.",
    category: "GARBAGE",
    severity: "HIGH",
    status: "ASSIGNED",
    priorityScore: 81,
    aiConfidence: 0.93,
    aiSummary: "Illegal mixed waste dump at public park entrance. Hazard to pedestrians and public health. Requires same-day clearance.",
    latitude: 10.7923,
    longitude: 79.1445,
    address: "Sivaganga Park Entrance, South Rampart St, Thanjavur - 613001",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    submittedBy: { id: "user_003", name: "Divya Rajendran", username: "divya_r", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=divya" },
    upvotes: 29,
    hasUserUpvoted: false,
    verifications: 11,
    comments: 3,
    assignedTo: { type: "worker", name: "Kumar Selvam", workerId: "user_004" },
    captureMethod: "UPLOAD",
    createdAt: "2026-06-22T14:30:00Z",
    updatedAt: "2026-06-23T11:00:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-22T14:30:00Z" },
      { status: "ASSIGNED", changedAt: "2026-06-23T11:00:00Z", changedBy: "Priya Subramaniam" },
    ],
  },
  {
    id: "rpt_003",
    title: "Major water pipe burst flooding Town Hall road",
    description: "Main water supply pipe has burst, flooding the entire street. Gallons of drinking water are being wasted.",
    category: "WATER_LEAK",
    severity: "CRITICAL",
    status: "RESOLVED",
    priorityScore: 98,
    aiConfidence: 0.99,
    aiSummary: "Active major water leak flooding public road. High urgency due to resource waste and infrastructure damage.",
    latitude: 10.9602,
    longitude: 79.3845,
    address: "Town Hall Road, Kumbakonam - 612001",
    imageUrl: "https://images.unsplash.com/photo-1584793610264-a5e23730245a?w=800",
    submittedBy: { id: "user_005", name: "Lakshmi Narayanan", username: "lakshmi_n", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=lakshmi" },
    upvotes: 89,
    hasUserUpvoted: false,
    verifications: 34,
    comments: 12,
    assignedTo: { type: "department", name: "Water & Drainage" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-21T07:15:00Z",
    updatedAt: "2026-06-21T16:45:00Z",
    resolvedAt: "2026-06-21T16:45:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-21T07:15:00Z" },
      { status: "IN_PROGRESS", changedAt: "2026-06-21T09:00:00Z" },
      { status: "RESOLVED", changedAt: "2026-06-21T16:45:00Z", note: "Leak fixed and pipe replaced." },
    ],
  },
  {
    id: "rpt_004",
    title: "Fallen tree blocking entire Anna Nagar main street",
    description: "A huge neem tree was uprooted during last night's storm and is completely blocking traffic. Power lines are tangled in the branches.",
    category: "OBSTRUCTION",
    severity: "CRITICAL",
    status: "ESCALATED",
    priorityScore: 95,
    aiConfidence: 0.96,
    aiSummary: "Large fallen tree blocking roadway with entangled power lines. Requires coordinated response from forestry and electrical departments.",
    latitude: 11.1400,
    longitude: 79.0789,
    address: "Anna Nagar Main Road, Ariyalur - 621704",
    imageUrl: "https://images.unsplash.com/photo-1517457211116-f6c125df977e?w=800",
    submittedBy: { id: "user_013", name: "Suresh Pillai", username: "suresh_p", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=suresh" },
    upvotes: 56,
    hasUserUpvoted: false,
    verifications: 22,
    comments: 8,
    assignedTo: { type: "department", name: "Emergency Services" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-24T06:30:00Z",
    updatedAt: "2026-06-24T08:15:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-24T06:30:00Z" },
      { status: "ESCALATED", changedAt: "2026-06-24T08:15:00Z", note: "Requires heavy machinery and electrical grid shutdown." },
    ],
  },
  {
    id: "rpt_005",
    title: "Broken streetlights along Bypass Road",
    description: "A stretch of about 5 streetlights is completely dead. Very dangerous for night driving and pedestrians.",
    category: "STREETLIGHT",
    severity: "MEDIUM",
    status: "OPEN",
    priorityScore: 55,
    aiConfidence: 0.88,
    aiSummary: "Multiple non-functioning streetlights reported on major road. Nighttime visibility hazard.",
    latitude: 10.8250,
    longitude: 78.6820,
    address: "Bypass Road near Toll Plaza, Trichy - 620001",
    imageUrl: "https://images.unsplash.com/photo-1494526585095-c41746248156?w=800",
    submittedBy: { id: "user_015", name: "Vignesh Shivan", username: "vignesh_s", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=vignesh" },
    upvotes: 14,
    hasUserUpvoted: false,
    verifications: 5,
    comments: 1,
    captureMethod: "UPLOAD",
    createdAt: "2026-06-23T19:45:00Z",
    updatedAt: "2026-06-23T19:45:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-23T19:45:00Z" },
    ],
  },
  {
    id: "rpt_006",
    title: "Open manhole on pedestrian walkway",
    description: "The concrete cover of the manhole is broken and partially missing. A child or elderly person could easily fall in.",
    category: "INFRASTRUCTURE",
    severity: "CRITICAL",
    status: "ASSIGNED",
    priorityScore: 92,
    aiConfidence: 0.95,
    aiSummary: "Missing or damaged manhole cover on pedestrian path. Severe fall hazard.",
    latitude: 10.7820,
    longitude: 79.1350,
    address: "Medical College Road, Thanjavur - 613004",
    imageUrl: "https://images.unsplash.com/photo-1628186105809-b68a51352e46?w=800",
    submittedBy: { id: "user_009", name: "Karthik Raja", username: "karthik_r", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=karthik" },
    upvotes: 38,
    hasUserUpvoted: false,
    verifications: 15,
    comments: 4,
    assignedTo: { type: "department", name: "Roads & Infrastructure" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-22T11:20:00Z",
    updatedAt: "2026-06-22T15:00:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-22T11:20:00Z" },
      { status: "ASSIGNED", changedAt: "2026-06-22T15:00:00Z" },
    ],
  },
  {
    id: "rpt_007",
    title: "Traffic signal completely off at 4-road junction",
    description: "The signals are completely blank, causing huge traffic snarls and near-accidents since morning.",
    category: "TRAFFIC",
    severity: "HIGH",
    status: "IN_PROGRESS",
    priorityScore: 85,
    aiConfidence: 0.91,
    aiSummary: "Non-functioning traffic signal at major intersection. High risk of collision.",
    latitude: 10.9650,
    longitude: 79.3880,
    address: "Bypass Junction, Kumbakonam - 612001",
    imageUrl: "https://images.unsplash.com/photo-1558066538-4e899cb2b6a5?w=800",
    submittedBy: { id: "user_011", name: "Ramesh Babu", username: "ramesh_b", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ramesh" },
    upvotes: 62,
    hasUserUpvoted: false,
    verifications: 28,
    comments: 9,
    assignedTo: { type: "department", name: "Traffic Management" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-24T08:45:00Z",
    updatedAt: "2026-06-24T10:30:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-24T08:45:00Z" },
      { status: "IN_PROGRESS", changedAt: "2026-06-24T10:30:00Z" },
    ],
  },
  {
    id: "rpt_008",
    title: "Overflowing drainage causing severe foul smell",
    description: "Underground sewage line seems blocked. Dirty water is flowing onto the street right outside residential homes.",
    category: "DRAINAGE",
    severity: "HIGH",
    status: "OPEN",
    priorityScore: 78,
    aiConfidence: 0.89,
    aiSummary: "Sewage overflow in residential area. Health and sanitation hazard.",
    latitude: 10.9100,
    longitude: 79.2800,
    address: "North Street, Papanasam - 614205",
    imageUrl: "https://images.unsplash.com/photo-1541888086825-63518ee11855?w=800",
    submittedBy: { id: "user_007", name: "Aisha Begum", username: "aisha_b", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha" },
    upvotes: 41,
    hasUserUpvoted: false,
    verifications: 12,
    comments: 7,
    captureMethod: "UPLOAD",
    createdAt: "2026-06-23T16:10:00Z",
    updatedAt: "2026-06-23T16:10:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-23T16:10:00Z" },
    ],
  },
  {
    id: "rpt_009",
    title: "Stray dog pack aggressive behavior",
    description: "A pack of 6-7 stray dogs has been chasing two-wheelers and growling at pedestrians near the school zone.",
    category: "ANIMAL",
    severity: "MEDIUM",
    status: "RESOLVED",
    priorityScore: 65,
    aiConfidence: 0.75,
    aiSummary: "Report of aggressive stray animals near school zone. Requires animal control intervention.",
    latitude: 10.7950,
    longitude: 79.1300,
    address: "Near SRV School, Thanjavur - 613005",
    imageUrl: "https://images.unsplash.com/photo-1544568100-847a948585b9?w=800",
    submittedBy: { id: "user_demo_citizen_001", name: "Arjun Mehta", username: "arjun_m", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=arjun" },
    upvotes: 18,
    hasUserUpvoted: false,
    verifications: 6,
    comments: 2,
    assignedTo: { type: "department", name: "Sanitation & Waste Management" },
    captureMethod: "UPLOAD",
    createdAt: "2026-06-15T09:20:00Z",
    updatedAt: "2026-06-16T14:00:00Z",
    resolvedAt: "2026-06-16T14:00:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-15T09:20:00Z" },
      { status: "RESOLVED", changedAt: "2026-06-16T14:00:00Z", note: "Animal control team relocated the pack safely." },
    ],
  },
  {
    id: "rpt_010",
    title: "Broken park bench and swing",
    description: "The main swing set chain is broken and a concrete bench is smashed. Unsafe for kids to play.",
    category: "INFRASTRUCTURE",
    severity: "LOW",
    status: "OPEN",
    priorityScore: 35,
    aiConfidence: 0.94,
    aiSummary: "Damaged playground equipment and seating in public park. Low urgency.",
    latitude: 10.8200,
    longitude: 78.6850,
    address: "Cantonment Park, Trichy - 620001",
    imageUrl: "https://images.unsplash.com/photo-1594498653385-d5172c532c00?w=800",
    submittedBy: { id: "user_010", name: "Meena Iyer", username: "meena_i", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=meena" },
    upvotes: 8,
    hasUserUpvoted: false,
    verifications: 2,
    comments: 0,
    captureMethod: "CAMERA",
    createdAt: "2026-06-20T17:30:00Z",
    updatedAt: "2026-06-20T17:30:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-20T17:30:00Z" },
    ],
  },
  {
    id: "rpt_011",
    title: "Leaking public water tap",
    description: "The valve on the public drinking water tap is broken. Water has been continuously running for 2 days.",
    category: "WATER_LEAK",
    severity: "MEDIUM",
    status: "RESOLVED",
    priorityScore: 50,
    aiConfidence: 0.90,
    aiSummary: "Faulty public tap causing continuous water wastage. Needs valve replacement.",
    latitude: 11.1350,
    longitude: 79.0800,
    address: "Market Road, Ariyalur - 621704",
    imageUrl: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800",
    submittedBy: { id: "user_013", name: "Suresh Pillai", username: "suresh_p", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=suresh" },
    upvotes: 12,
    hasUserUpvoted: false,
    verifications: 4,
    comments: 1,
    assignedTo: { type: "worker", name: "Senthil Vel", workerId: "user_008" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-18T10:00:00Z",
    updatedAt: "2026-06-19T11:30:00Z",
    resolvedAt: "2026-06-19T11:30:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-18T10:00:00Z" },
      { status: "ASSIGNED", changedAt: "2026-06-18T14:00:00Z" },
      { status: "RESOLVED", changedAt: "2026-06-19T11:30:00Z", note: "New tap valve installed." },
    ],
  },
  {
    id: "rpt_012",
    title: "Pothole clusters on bridge approach",
    description: "Multiple small and medium potholes forming right at the approach of the new overbridge.",
    category: "POTHOLE",
    severity: "HIGH",
    status: "ASSIGNED",
    priorityScore: 72,
    aiConfidence: 0.92,
    aiSummary: "Cluster of potholes on bridge approach road. Potential traffic disruption.",
    latitude: 10.9550,
    longitude: 79.3900,
    address: "New Overbridge, Kumbakonam - 612001",
    imageUrl: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=800",
    submittedBy: { id: "user_003", name: "Divya Rajendran", username: "divya_r", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=divya" },
    upvotes: 21,
    hasUserUpvoted: false,
    verifications: 8,
    comments: 2,
    assignedTo: { type: "worker", name: "Murugan K", workerId: "user_006" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-21T08:20:00Z",
    updatedAt: "2026-06-22T09:00:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-21T08:20:00Z" },
      { status: "ASSIGNED", changedAt: "2026-06-22T09:00:00Z" },
    ],
  },
  {
    id: "rpt_013",
    title: "Overflowing public dustbin",
    description: "The large green bin hasn't been cleared in 3 days. Garbage spilling onto the road.",
    category: "GARBAGE",
    severity: "MEDIUM",
    status: "RESOLVED",
    priorityScore: 45,
    aiConfidence: 0.85,
    aiSummary: "Overfilled municipal waste bin requiring collection.",
    latitude: 10.7900,
    longitude: 79.1400,
    address: "South Main Street, Thanjavur - 613001",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    submittedBy: { id: "user_demo_citizen_001", name: "Arjun Mehta", username: "arjun_m", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=arjun" },
    upvotes: 16,
    hasUserUpvoted: false,
    verifications: 5,
    comments: 0,
    assignedTo: { type: "department", name: "Sanitation & Waste Management" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-19T07:45:00Z",
    updatedAt: "2026-06-19T14:20:00Z",
    resolvedAt: "2026-06-19T14:20:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-19T07:45:00Z" },
      { status: "RESOLVED", changedAt: "2026-06-19T14:20:00Z", note: "Garbage truck cleared the bin." },
    ],
  },
  {
    id: "rpt_014",
    title: "Damaged bus shelter roof",
    description: "The metal roofing of the bus stop blew away in the wind. No shelter for commuters during rain.",
    category: "INFRASTRUCTURE",
    severity: "MEDIUM",
    status: "OPEN",
    priorityScore: 52,
    aiConfidence: 0.87,
    aiSummary: "Missing roof on public transit shelter. Needs repair.",
    latitude: 10.9150,
    longitude: 79.2850,
    address: "Main Bus Stop, Papanasam - 614205",
    imageUrl: "https://images.unsplash.com/photo-1628186105809-b68a51352e46?w=800",
    submittedBy: { id: "user_014", name: "Deepa Krishnan", username: "deepa_k", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=deepa" },
    upvotes: 24,
    hasUserUpvoted: false,
    verifications: 7,
    comments: 3,
    captureMethod: "UPLOAD",
    createdAt: "2026-06-22T13:10:00Z",
    updatedAt: "2026-06-22T13:10:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-22T13:10:00Z" },
    ],
  },
  {
    id: "rpt_015",
    title: "Exposed electrical wires near school",
    description: "An electrical junction box is hanging open with live wires exposed on the pavement where kids walk.",
    category: "ELECTRICAL",
    severity: "CRITICAL",
    status: "ESCALATED",
    priorityScore: 99,
    aiConfidence: 0.98,
    aiSummary: "Exposed live wiring in pedestrian area. Severe electrocution risk.",
    latitude: 10.8280,
    longitude: 78.6800,
    address: "Near St. John's School, Trichy - 620001",
    imageUrl: "https://images.unsplash.com/photo-1544715568-ad2327de85e4?w=800",
    submittedBy: { id: "user_005", name: "Lakshmi Narayanan", username: "lakshmi_n", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=lakshmi" },
    upvotes: 75,
    hasUserUpvoted: false,
    verifications: 30,
    comments: 11,
    assignedTo: { type: "department", name: "Electrical & Street Lighting" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-24T10:05:00Z",
    updatedAt: "2026-06-24T10:45:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-24T10:05:00Z" },
      { status: "ESCALATED", changedAt: "2026-06-24T10:45:00Z", note: "Immediate power isolation required." },
    ],
  },
  {
    id: "rpt_016",
    title: "Clogged stormwater drain",
    description: "Drain is completely choked with plastic waste. Water is already pooling on the street.",
    category: "DRAINAGE",
    severity: "MEDIUM",
    status: "RESOLVED",
    priorityScore: 58,
    aiConfidence: 0.90,
    aiSummary: "Blocked surface drain causing minor localized flooding.",
    latitude: 11.1450,
    longitude: 79.0820,
    address: "College Road, Ariyalur - 621704",
    imageUrl: "https://images.unsplash.com/photo-1541888086825-63518ee11855?w=800",
    submittedBy: { id: "user_013", name: "Suresh Pillai", username: "suresh_p", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=suresh" },
    upvotes: 11,
    hasUserUpvoted: false,
    verifications: 4,
    comments: 0,
    assignedTo: { type: "worker", name: "Senthil Vel", workerId: "user_008" },
    captureMethod: "UPLOAD",
    createdAt: "2026-06-17T08:30:00Z",
    updatedAt: "2026-06-18T10:15:00Z",
    resolvedAt: "2026-06-18T10:15:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-17T08:30:00Z" },
      { status: "RESOLVED", changedAt: "2026-06-18T10:15:00Z", note: "Drain cleared of plastic debris." },
    ],
  },
  {
    id: "rpt_017",
    title: "Graffiti on historical monument wall",
    description: "Someone has spray-painted modern graffiti on the outer boundary wall of the Brihadeeswara Temple approach.",
    category: "VANDALISM",
    severity: "MEDIUM",
    status: "IN_PROGRESS",
    priorityScore: 68,
    aiConfidence: 0.93,
    aiSummary: "Vandalism/Graffiti detected on heritage structure boundary.",
    latitude: 10.7830,
    longitude: 79.1320,
    address: "Temple Approach Road, Thanjavur - 613001",
    imageUrl: "https://images.unsplash.com/photo-1517457211116-f6c125df977e?w=800",
    submittedBy: { id: "user_demo_citizen_001", name: "Arjun Mehta", username: "arjun_m", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=arjun" },
    upvotes: 52,
    hasUserUpvoted: false,
    verifications: 16,
    comments: 8,
    assignedTo: { type: "department", name: "Parks & Public Spaces" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-23T14:20:00Z",
    updatedAt: "2026-06-24T09:30:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-23T14:20:00Z" },
      { status: "IN_PROGRESS", changedAt: "2026-06-24T09:30:00Z", note: "Specialized cleaning crew dispatched to avoid damaging stone." },
    ],
  },
  {
    id: "rpt_018",
    title: "Dead animal on highway",
    description: "Carcass of a stray dog hit by a vehicle is lying in the middle lane.",
    category: "ANIMAL",
    severity: "MEDIUM",
    status: "ASSIGNED",
    priorityScore: 60,
    aiConfidence: 0.86,
    aiSummary: "Animal carcass on roadway. Hygiene and minor traffic issue.",
    latitude: 10.9700,
    longitude: 79.3920,
    address: "Chennai Bypass, Kumbakonam - 612001",
    imageUrl: "https://images.unsplash.com/photo-1544568100-847a948585b9?w=800",
    submittedBy: { id: "user_011", name: "Ramesh Babu", username: "ramesh_b", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ramesh" },
    upvotes: 9,
    hasUserUpvoted: false,
    verifications: 3,
    comments: 0,
    assignedTo: { type: "worker", name: "Murugan K", workerId: "user_006" },
    captureMethod: "UPLOAD",
    createdAt: "2026-06-24T07:15:00Z",
    updatedAt: "2026-06-24T08:00:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-24T07:15:00Z" },
      { status: "ASSIGNED", changedAt: "2026-06-24T08:00:00Z" },
    ],
  },
  {
    id: "rpt_019",
    title: "Broken pavement blocks",
    description: "Pavement tiles are loose and broken, making it difficult for wheelchair users to pass.",
    category: "INFRASTRUCTURE",
    severity: "LOW",
    status: "OPEN",
    priorityScore: 40,
    aiConfidence: 0.89,
    aiSummary: "Damaged pedestrian walkway tiles. Accessibility concern.",
    latitude: 10.8220,
    longitude: 78.6880,
    address: "Thillai Nagar Main Road, Trichy - 620018",
    imageUrl: "https://images.unsplash.com/photo-1628186105809-b68a51352e46?w=800",
    submittedBy: { id: "user_010", name: "Meena Iyer", username: "meena_i", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=meena" },
    upvotes: 15,
    hasUserUpvoted: false,
    verifications: 6,
    comments: 2,
    captureMethod: "CAMERA",
    createdAt: "2026-06-23T11:45:00Z",
    updatedAt: "2026-06-23T11:45:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-23T11:45:00Z" },
    ],
  },
  {
    id: "rpt_020",
    title: "Unauthorized hoarding covering traffic sign",
    description: "A huge political banner has been tied directly over the speed limit and junction warning signs.",
    category: "OBSTRUCTION",
    severity: "HIGH",
    status: "RESOLVED",
    priorityScore: 75,
    aiConfidence: 0.91,
    aiSummary: "Illegal banner obstructing vital traffic signage. Safety risk.",
    latitude: 10.7880,
    longitude: 79.1360,
    address: "Manojipatti Junction, Thanjavur - 613004",
    imageUrl: "https://images.unsplash.com/photo-1517457211116-f6c125df977e?w=800",
    submittedBy: { id: "user_012", name: "Anjali Devi", username: "anjali_d", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=anjali" },
    upvotes: 31,
    hasUserUpvoted: false,
    verifications: 10,
    comments: 5,
    assignedTo: { type: "department", name: "Traffic Management" },
    captureMethod: "UPLOAD",
    createdAt: "2026-06-20T14:30:00Z",
    updatedAt: "2026-06-21T09:00:00Z",
    resolvedAt: "2026-06-21T09:00:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-20T14:30:00Z" },
      { status: "RESOLVED", changedAt: "2026-06-21T09:00:00Z", note: "Banner removed and confiscated." },
    ],
  },
  {
    id: "rpt_021",
    title: "Flooding in subway after rain",
    description: "The railway underpass is filled with 2 feet of water after yesterday's shower. Pumps aren't working.",
    category: "DRAINAGE",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    priorityScore: 96,
    aiConfidence: 0.96,
    aiSummary: "Flooded vehicle underpass. Major traffic blockage and potential vehicle damage.",
    latitude: 10.9620,
    longitude: 79.3820,
    address: "Railway Station Underpass, Kumbakonam - 612001",
    imageUrl: "https://images.unsplash.com/photo-1584793610264-a5e23730245a?w=800",
    submittedBy: { id: "user_003", name: "Divya Rajendran", username: "divya_r", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=divya" },
    upvotes: 82,
    hasUserUpvoted: false,
    verifications: 25,
    comments: 14,
    assignedTo: { type: "department", name: "Roads & Infrastructure" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-24T07:00:00Z",
    updatedAt: "2026-06-24T10:00:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-24T07:00:00Z" },
      { status: "IN_PROGRESS", changedAt: "2026-06-24T10:00:00Z", note: "Portable heavy-duty pumps deployed." },
    ],
  },
  {
    id: "rpt_022",
    title: "Streetlight pole rusted and leaning",
    description: "The base of the metal pole is completely rusted through. It is leaning dangerously over the sidewalk.",
    category: "STREETLIGHT",
    severity: "HIGH",
    status: "OPEN",
    priorityScore: 82,
    aiConfidence: 0.94,
    aiSummary: "Structurally compromised lighting pole. High risk of collapse.",
    latitude: 10.9120,
    longitude: 79.2820,
    address: "Bazaar Street, Papanasam - 614205",
    imageUrl: "https://images.unsplash.com/photo-1494526585095-c41746248156?w=800",
    submittedBy: { id: "user_007", name: "Aisha Begum", username: "aisha_b", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha" },
    upvotes: 27,
    hasUserUpvoted: false,
    verifications: 9,
    comments: 1,
    captureMethod: "CAMERA",
    createdAt: "2026-06-23T18:20:00Z",
    updatedAt: "2026-06-23T18:20:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-23T18:20:00Z" },
    ],
  },
  {
    id: "rpt_023",
    title: "Construction debris dumped on vacant lot",
    description: "Truckloads of rubble and sand have been dumped illegally in the empty plot next to our layout.",
    category: "GARBAGE",
    severity: "MEDIUM",
    status: "ASSIGNED",
    priorityScore: 54,
    aiConfidence: 0.90,
    aiSummary: "Large scale illegal dumping of construction material.",
    latitude: 11.1420,
    longitude: 79.0850,
    address: "Periyar Nagar Extension, Ariyalur - 621704",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    submittedBy: { id: "user_013", name: "Suresh Pillai", username: "suresh_p", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=suresh" },
    upvotes: 19,
    hasUserUpvoted: false,
    verifications: 7,
    comments: 3,
    assignedTo: { type: "worker", name: "Senthil Vel", workerId: "user_008" },
    captureMethod: "UPLOAD",
    createdAt: "2026-06-22T09:15:00Z",
    updatedAt: "2026-06-23T10:00:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-22T09:15:00Z" },
      { status: "ASSIGNED", changedAt: "2026-06-23T10:00:00Z" },
    ],
  },
  {
    id: "rpt_024",
    title: "Fire in garbage dump",
    description: "Someone set fire to a large pile of garbage. Toxic black smoke is entering nearby houses.",
    category: "GARBAGE",
    severity: "CRITICAL",
    status: "RESOLVED",
    priorityScore: 97,
    aiConfidence: 0.95,
    aiSummary: "Active fire in waste pile causing toxic smoke. Immediate emergency response needed.",
    latitude: 10.7850,
    longitude: 79.1420,
    address: "Karanthai area, Thanjavur - 613002",
    imageUrl: "https://images.unsplash.com/photo-1541888086825-63518ee11855?w=800",
    submittedBy: { id: "user_demo_citizen_001", name: "Arjun Mehta", username: "arjun_m", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=arjun" },
    upvotes: 66,
    hasUserUpvoted: false,
    verifications: 19,
    comments: 15,
    assignedTo: { type: "department", name: "Emergency Services" },
    captureMethod: "CAMERA",
    createdAt: "2026-06-19T18:00:00Z",
    updatedAt: "2026-06-19T19:30:00Z",
    resolvedAt: "2026-06-19T19:30:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-19T18:00:00Z" },
      { status: "ESCALATED", changedAt: "2026-06-19T18:05:00Z", note: "Fire department notified." },
      { status: "RESOLVED", changedAt: "2026-06-19T19:30:00Z", note: "Fire extinguished." },
    ],
  },
  {
    id: "rpt_025",
    title: "Faded zebra crossing lines",
    description: "The pedestrian crossing paint has completely faded outside the primary school.",
    category: "INFRASTRUCTURE",
    severity: "LOW",
    status: "OPEN",
    priorityScore: 42,
    aiConfidence: 0.82,
    aiSummary: "Faded road markings at pedestrian crossing. Maintenance required.",
    latitude: 10.8260,
    longitude: 78.6830,
    address: "Outside Govt Primary School, Thillai Nagar, Trichy - 620018",
    imageUrl: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=800",
    submittedBy: { id: "user_015", name: "Vignesh Shivan", username: "vignesh_s", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=vignesh" },
    upvotes: 12,
    hasUserUpvoted: false,
    verifications: 3,
    comments: 0,
    captureMethod: "UPLOAD",
    createdAt: "2026-06-24T09:10:00Z",
    updatedAt: "2026-06-24T09:10:00Z",
    statusHistory: [
      { status: "OPEN", changedAt: "2026-06-24T09:10:00Z" },
    ],
  }
];
