export type DemoRole = "CITIZEN" | "ADMIN" | "WORKER" | "SUPERADMIN";

export interface DemoUser {
  id: string;
  name: string;
  username: string;
  email: string;
  avatarUrl: string;
  role: DemoRole;
  city?: string;
  age?: number;
  gender?: string;
  bio?: string;
  xp?: number;
  level?: string;
  reportsSubmitted?: number;
  reportsVerified?: number;
  joinedAt: string;
}

export const demoUsers: Record<string, DemoUser> = {
  citizen: {
    id: "user_demo_citizen_001",
    name: "Arjun Mehta",
    username: "arjun_m",
    email: "arjun.mehta@demo.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=arjun",
    role: "CITIZEN",
    city: "Thanjavur",
    age: 28,
    gender: "male",
    bio: "Civic enthusiast. Reporting issues since 2024.",
    xp: 1340,
    level: "Community Guardian",
    reportsSubmitted: 12,
    reportsVerified: 34,
    joinedAt: "2024-03-15",
  },
  admin: {
    id: "user_demo_admin_001",
    name: "Priya Subramaniam",
    username: "priya_admin",
    email: "priya.s@municipality.gov.in",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    role: "ADMIN",
    city: "Thanjavur",
    joinedAt: "2023-11-01",
  },
};

export const allDemoUsers: DemoUser[] = [
  demoUsers.citizen,
  demoUsers.admin,
  {
    id: "user_003",
    name: "Divya Rajendran",
    username: "divya_r",
    email: "divya@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=divya",
    role: "CITIZEN",
    city: "Kumbakonam",
    xp: 450,
    level: "Civic Observer",
    reportsSubmitted: 4,
    joinedAt: "2025-01-10",
  },
  {
    id: "user_004",
    name: "Kumar Selvam",
    username: "kumar_s",
    email: "kumar.worker@municipality.gov.in",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=kumar",
    role: "WORKER",
    city: "Thanjavur",
    joinedAt: "2022-06-15",
  },
  {
    id: "user_005",
    name: "Lakshmi Narayanan",
    username: "lakshmi_n",
    email: "lakshmi@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=lakshmi",
    role: "CITIZEN",
    city: "Trichy",
    xp: 2400,
    level: "Urban Hero",
    reportsSubmitted: 23,
    joinedAt: "2023-09-05",
  },
  {
    id: "user_006",
    name: "Murugan K",
    username: "murugan_k",
    email: "murugan.worker@municipality.gov.in",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=murugan",
    role: "WORKER",
    city: "Kumbakonam",
    joinedAt: "2021-04-12",
  },
  {
    id: "user_007",
    name: "Aisha Begum",
    username: "aisha_b",
    email: "aisha@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha",
    role: "CITIZEN",
    city: "Papanasam",
    xp: 890,
    level: "Active Citizen",
    reportsSubmitted: 8,
    joinedAt: "2024-11-20",
  },
  {
    id: "user_008",
    name: "Senthil Vel",
    username: "senthil_v",
    email: "senthil.worker@municipality.gov.in",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=senthil",
    role: "WORKER",
    city: "Ariyalur",
    joinedAt: "2023-02-28",
  },
  {
    id: "user_009",
    name: "Karthik Raja",
    username: "karthik_r",
    email: "karthik@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=karthik",
    role: "CITIZEN",
    city: "Thanjavur",
    xp: 120,
    level: "Newcomer",
    reportsSubmitted: 1,
    joinedAt: "2026-05-15",
  },
  {
    id: "user_010",
    name: "Meena Iyer",
    username: "meena_i",
    email: "meena@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=meena",
    role: "CITIZEN",
    city: "Trichy",
    xp: 560,
    level: "Civic Observer",
    reportsSubmitted: 5,
    joinedAt: "2025-08-11",
  },
  {
    id: "user_011",
    name: "Ramesh Babu",
    username: "ramesh_b",
    email: "ramesh@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ramesh",
    role: "CITIZEN",
    city: "Kumbakonam",
    xp: 50,
    level: "Newcomer",
    reportsSubmitted: 1,
    joinedAt: "2026-06-01",
  },
  {
    id: "user_012",
    name: "Anjali Devi",
    username: "anjali_d",
    email: "anjali@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=anjali",
    role: "CITIZEN",
    city: "Thanjavur",
    xp: 1800,
    level: "Community Guardian",
    reportsSubmitted: 16,
    joinedAt: "2024-01-25",
  },
  {
    id: "user_013",
    name: "Suresh Pillai",
    username: "suresh_p",
    email: "suresh@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=suresh",
    role: "CITIZEN",
    city: "Ariyalur",
    xp: 320,
    level: "Contributor",
    reportsSubmitted: 3,
    joinedAt: "2025-12-05",
  },
  {
    id: "user_014",
    name: "Deepa Krishnan",
    username: "deepa_k",
    email: "deepa@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=deepa",
    role: "CITIZEN",
    city: "Papanasam",
    xp: 950,
    level: "Active Citizen",
    reportsSubmitted: 9,
    joinedAt: "2024-07-18",
  },
  {
    id: "user_015",
    name: "Vignesh Shivan",
    username: "vignesh_s",
    email: "vignesh@example.com",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=vignesh",
    role: "CITIZEN",
    city: "Trichy",
    xp: 1500,
    level: "Community Guardian",
    reportsSubmitted: 14,
    joinedAt: "2024-05-12",
  }
];
